// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811091356_AddContentTypeToAttachment")]
    partial class AddContentTypeToAttachment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Achievement", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RollNumber");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Backend.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backend.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementRollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertificateRollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementRollNumber");

                    b.HasIndex("CertificateRollNumber");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("Backend.Models.Certificate", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RollNumber");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Backend.Models.CodingProfile", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CSES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeForces")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollNumber");

                    b.ToTable("CodingProfiles");
                });

            modelBuilder.Entity("Backend.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Pfp")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("RollNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Backend.Models.Attachment", b =>
                {
                    b.HasOne("Backend.Models.Achievement", null)
                        .WithMany("Achievements")
                        .HasForeignKey("AchievementRollNumber");

                    b.HasOne("Backend.Models.Certificate", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CertificateRollNumber");
                });

            modelBuilder.Entity("Backend.Models.Achievement", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("Backend.Models.Certificate", b =>
                {
                    b.Navigation("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
